#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1574068523                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : # https://emilbaehr.com                     # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Write a short tagline for your app.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alerting Options, LLC
your_link                                 :                      
your_city                                 :                                 
email_address                             : alertingoptions@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : # https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Create Meal Plan
    description                           : Take the stress out of mealtimes by allowing Menyou to generate a delicious and simple meal plan specified to your needs.
    fontawesome_icon_name                 : circle-plus
    
  - title                                 : Simple Meals
    description                           : Our meals were created to be quick and simple, saving you time and stress.
    fontawesome_icon_name                 : utensils

  - title                                 : Grocery List
    description                           : A grocery list will be generated specific to your meals to ensure you have everything you need to make our delicious meals.
    fontawesome_icon_name                 : bag-shopping

  - title                                 : Prep meals step by step
    description                           : Simple and concise step by step instructions will appear on your device to help you easily prepare your meals. Everything you need for each step will be visible on the screen.
    fontawesome_icon_name                 : circle-info

  - title                                 : Groceries Delivered to Your Door
    description                           : Experience the convenience of having your groceries added to your cart and delivered to your home.
    fontawesome_icon_name                 : truck
  
  - title                                 : Groceries with a Smart Pantry
    description                           : Meal plan with a smart pantry that remembers your grocery items.
    fontawesome_icon_name                 : bookmark

  - title                                 : Family Meal Planning Made Easy
    description                           : Collaborate and share meal plans with your family hassle-free.
    fontawesome_icon_name                 : people-roof

  - title                                 : # Social Links
    description                           : # Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # link

  - title                                 : # FontAwesome Support
    description                           : # Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
    fontawesome_icon_name                 : # info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#02CDAC"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#0f5c64"
feature_text_color                        : "#030319"

feature_icons_foreground_color            : "#02CDAC"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#030319"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
